FROM nginx:alpine
COPY index.html /usr/share/nginx/html/
COPY board.html /usr/share/nginx/html/
COPY graph.html /usr/share/nginx/html/
COPY map.html /usr/share/nginx/html/
COPY cases.html /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
